#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Apr 20 21:31:13 PDT 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_counter_behav -key {Behavioral:sim_1:Functional:tb_counter} -tclbatch tb_counter.tcl -log simulate.log"
xsim tb_counter_behav -key {Behavioral:sim_1:Functional:tb_counter} -tclbatch tb_counter.tcl -log simulate.log

